# Generated by Django 4.2.7 on 2024-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0002_alter_equipo_id_alter_facultad_id_alter_horario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='foto',
            field=models.FileField(default='hola mundo', upload_to='laboratorio'),
        ),
    ]
